on: [workflow_dispatch]
jobs:
  bootstrap:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: bin/bootstrap
      - run: tar -cvf ../fileinfo.tar --exclude .git .
      - run: mv ../fileinfo.tar .
      - uses: actions/upload-artifact@v2
        with:
          name: bootstrap-output
          path: fileinfo.tar

  is-act:
    runs-on: ubuntu-latest
    outputs: { result: "${{ env.ACT }}" }
    steps: [{ run: true }] ## Keep the schema happy

  docker-steps:
    if: false
    runs-on: ubuntu-latest
    steps: &docker-steps
      # Setup multi-platform support for docker
      - uses: docker/setup-qemu-action@v1.2.0

      # Try to create a container for the given platform and image
      - name: Create container
        shell: bash
        run: |
          set +e
          cont=$(docker run --pull=missing --init --detach --platform linux/${{ matrix.platform }} ${{ env.image }} tail -f /dev/null)
          echo "Docker exit code: $?"
          set -e

          echo "cont=$cont" >> $GITHUB_ENV
          echo "cont=$cont"

          if test "x$cont" = "x"; then
            echo "::error ::Container launch failed (${{ matrix.platform }}, ${{ env.image }})."
            exit 1
          fi

      # Check platforms
      - run: whoami
      - run: uname -a
      - run: echo "user=$(docker exec "$cont" whoami)" >> $GITHUB_ENV
      - run: echo "user=$user"
      - run: docker exec "$cont" uname -a

      # Create the working directory
      - run: echo "workdir=/workdir" >> $GITHUB_ENV
      - run: echo "workdir=$workdir"
      - run: docker exec --user=root "$cont" mkdir "$workdir"

      # Copy the artifact to the working directory
      - uses: actions/download-artifact@v2
        with: { name: bootstrap-output }
      - run: docker cp - <fileinfo.tar "$cont":"$workdir"
      - run: docker exec --user=root "$cont" chown -R "$user:$user" "$workdir"

      # Install dependencies
      - run: docker exec --user=root "$cont" "$workdir"/bin/install-deps

      # Build
      - run: docker exec --workdir="$workdir" "$cont" ./configure
      - run: docker exec --workdir="$workdir" "$cont" cat src/config.h
      - run: docker exec --workdir="$workdir" "$cont" cat src/headers.h
      - run: docker exec --workdir="$workdir" "$cont" cat src/fileinfo/static.h
      - run: docker exec --workdir="$workdir" "$cont" make
      - run: docker exec --workdir="$workdir" "$cont" make check

      # Cleanup
      - run: docker stop "$cont"
      - run: docker rm --force --volumes "$cont"
