  # shell:
  #   needs: bootstrap
  #   runs-on: windows-2019
  #   steps:
  #     - uses: actions/download-artifact@v2
  #       with: { name: bootstrap-output }
  #     - name: Setup tmate session
  #       uses: mxschmitt/action-tmate@v3

  windows:
    needs: bootstrap
    runs-on: windows-2019
    steps:
      - uses: actions/download-artifact@v2
        with: { name: bootstrap-output }
      - shell: C:\msys64\usr\bin\bash.exe {0}
        run: |
          exec 2>&1
          set +e
          set -x
          echo "$PATH"
          PATH=''
          PATH="$PATH:/c/msys64/usr/bin"
          PATH="$PATH:/c/vcpkg"
          PATH="$PATH:/c/tools/zstd"
          PATH="$PATH:/c/hostedtoolcache/windows/stack/2.7.3/x64"
          PATH="$PATH:/c/Program Files (x86)/Microsoft SDKs/Azure/CLI2/wbin"
          PATH="$PATH:/c/ProgramData/kind"
          PATH="$PATH:/c/Windows/system32"
          PATH="$PATH:/c/Windows"
          PATH="$PATH:/c/Windows/System32/Wbem"
          PATH="$PATH:/c/Windows/System32/WindowsPowerShell/v1.0"
          PATH="$PATH:/c/Windows/System32/OpenSSH"
          PATH="$PATH:/c/Program Files/Docker"
          PATH="$PATH:/c/Program Files/PowerShell/7"
          PATH="$PATH:/c/Program Files/OpenSSL/bin"
          PATH="$PATH:/c/Program Files/CMake/bin"
          PATH="$PATH:/c/Users/runneradmin/AppData/Local/Microsoft/WindowsApps"

          PATH="$PATH:/c/ProgramData/Chocolatey/bin"
          PATH="$PATH:/c/Strawberry/c/bin"

          PATH="/c/Program Files (x86)/Microsoft Visual Studio/2019/Enterprise/VC/Tools/MSVC/14.16.27023/bin/HostX64/x64:$PATH"

          tar -xvf fileinfo.tar
          ./configure
          cat config.log
          make check
      - run: dir
      - run: .\fileinfo-fields-dynamic

# /c/Program Files (x86)/Microsoft Visual Studio/2019/Enterprise/SDK/ScopeCppSDK/vc15/VC/bin/cl.exe
# /c/Program Files (x86)/Microsoft Visual Studio/2019/Enterprise/VC/Tools/MSVC/14.16.27023/bin/HostX64/arm/cl.exe

  # github-virtual-environments:
  #   needs: bootstrap
  #   runs-on: ${{ matrix.os }}
  #   strategy:
  #     fail-fast: false
  #     matrix:
  #       os:
  #         - ubuntu-20.04
  #         - ubuntu-18.04
  #         - macos-11
  #         - macos-10.15
  #         # - windows-2022
  #         # - windows-2019
  #         # - windows-2016
  #   steps:
  #     - uses: actions/download-artifact@v2
  #       with: { name: bootstrap-output }
  #     - run: tar -xvf fileinfo.tar
  #     - run: ./configure
  #     - run: cat src/config.h
  #     - run: cat src/fileinfo/static.h
  #     - run: make
  #     - run: make check

  # cross-platform-actions:
  #   needs: bootstrap
  #   runs-on: macos-10.15
  #   strategy:
  #     fail-fast: false
  #     matrix:
  #       os:
  #         - name: freebsd
  #           version: '13.0'
  #         - name: freebsd
  #           version: '12.2'
  #         # - name: openbsd # compiler flag error
  #         #   version: '6.9'
  #         # - name: openbsd # compiler flag error
  #         #   version: '6.8'
  #         # - name: netbsd # action fails
  #         #   version: '9.2'
  #   steps:
  #     - uses: actions/download-artifact@v2
  #       with: { name: bootstrap-output }
  #     - run: tar -xvf fileinfo.tar
  #     - name: Test on ${{ matrix.os.name }}
  #       uses: cross-platform-actions/action@v0.3.1
  #       with:
  #         operating_system: ${{ matrix.os.name }}
  #         version: ${{ matrix.os.version }}
  #         shell: bash
  #         run: |
  #           ./configure && \
  #           cat src/config.h && \
  #           cat src/fileinfo/static.h && \
  #           make && \
  #           make check

  # vmactions-freebsd:
  #   needs: bootstrap
  #   runs-on: macos-10.15
  #   steps:
  #     - uses: actions/download-artifact@v2
  #       with:
  #         name: bootstrap-output
  #     - run: tar -xvf fileinfo.tar
  #     - uses: vmactions/freebsd-vm@v0.1.5
  #       with:
  #         # prepare: |
  #         #   pkg install -y gcc
  #         run: |
  #           pkg install --help
  #           ./configure
  #           make

  # vmactions-solaris: # works but take a long time to run
  #   needs: bootstrap
  #   runs-on: macos-10.15
  #   steps:
  #     - uses: actions/download-artifact@v2
  #       with:
  #         name: bootstrap-output
  #     - run: tar -xvf fileinfo.tar
  #     - uses: vmactions/solaris-vm@v0.0.3
  #       with:
  #         prepare: |
  #           # pkgutil -U
  #           pkgutil -y -i gcc5core
  #         run: |
  #           pkgutil --help
  #           ./configure
  #           make
