## Docker images from https://hub.docker.com/u/multiarch
##
## Omitted Images:
## - qemu-user-static - The binaries for QEMU
## - crossbuild - Environment for producing binaries for multiple architectures
## - true - Contains just the `true` program
## - goxc - Build tool for Go
## - bussybox - No package manager

  docker-multiarch-alpine:
    env: { image: "multiarch/alpine:${{ matrix.arch }}-${{ matrix.version }}" }
    needs: bootstrap
    runs-on: ubuntu-latest
    steps: *docker-steps
    strategy:
      fail-fast: false
      matrix:
        platform:
          - amd64
        arch:
          - i386
          - ppc64le
          - arm64
          - x86_64
          - armv7
          - armhf
          - aarch64
          - x86
        version:
          - latest-stable
          - edge
          - v3.14
          - v3.13
          - v3.12
          - v3.11

  docker-multiarch-ubuntu-core:
    env: { platform: amd64, image: "multiarch/ubuntu-core:${{ matrix.arch }}-${{ matrix.version }}" }
    needs: bootstrap
    runs-on: ubuntu-latest
    steps: *docker-steps
    strategy:
      fail-fast: false
      matrix:
        platform:
          - amd64
        arch:
          - arm64
          - armhf
          - i386
          - ppc64el
          - s390x
          - x86_64
        version:
          - bionic
          - focal
          - trusty
          - xenial

  docker-multiarch-ubuntu-debootstrap:
    env: { platform: amd64, image: "multiarch/ubuntu-debootstrap:${{ matrix.arch }}-${{ matrix.version }}" }
    needs: bootstrap
    runs-on: ubuntu-latest
    steps: *docker-steps
    strategy:
      fail-fast: false
      matrix:
        platform:
          - amd64
        arch:
          - amd64
          - arm64
          - armhf
          - i386
          - ppc64el
          # - powerpc
        version:
          - bionic
          - bionic-slim
          - focal
          - focal-slim
          - trusty
          - trusty-slim
          - xenial
          - xenial-slim

  docker-multiarch-debian-debootstrap:
    env: { platform: amd64, image: "multiarch/debian-debootstrap:${{ matrix.arch }}-${{ matrix.version }}" }
    needs: bootstrap
    runs-on: ubuntu-latest
    steps: *docker-steps
    strategy:
      fail-fast: false
      matrix:
        platform:
          - amd64
        arch:
          - amd64
          - arm64
          - armel
          - armhf
          - i386
          # - mips
          - mips64el
          # - mipsel
          - powerpc
          - ppc64el
          - s390x
        version:
          - bullseye
          - bullseye-slim
          - buster
          - buster-slim
          - sid
          - sid-slim
          - stretch
          - stretch-slim

  docker-multiarch-fedora:
    env: { platform: amd64, image: "multiarch/fedora:${{ matrix.version }}-${{ matrix.arch }}" }
    needs: bootstrap
    runs-on: ubuntu-latest
    steps: *docker-steps
    strategy:
      fail-fast: false
      matrix:
        platform:
          - amd64
        arch:
          - aarch64
          - ppc64le
          - s390x
          - x86_64
        version:
          - 34
          - 33
          - 32
          - 31
          - 30
          - 29
          - 28
        exclude:
          - arch: s390x
            version: 28
          - arch: ppc64le
            version: 28
          - arch: ppc64le
            version: 30
          - arch: ppc64le
            version: 31
          - arch: ppc64le
            version: 32

  docker-multiarch-centos:
    env: { required: 1, platform: amd64, image: "multiarch/centos:${{ matrix.version }}-clean" }
    needs: bootstrap
    runs-on: ubuntu-latest
    steps: *docker-steps
    strategy:
      fail-fast: false
      matrix:
        platform:
          - amd64
        version:
          - 7
          - 7-aarch64
          - 7-amd64
          - 7-armhfp
          # - 7-i386
          # - 7-ppc64
          # - 7-ppc64le
          - 7.3
          - 7.3-aarch64
          - 7.3-amd64
          - 7.3-armhfp
          - 7.3-ppc64
          # - 7.3-ppc64le
          - 7.6
          - 7.6-amd64
          - 7.6-armhfp
          - aarch64
          - amd64
          - armhfp
          # - i386
          - latest
          # - ppc64
          # - ppc64le

  docker-multiarch-voidlinux:
    env: { required: 1, platform: amd64, image: "multiarch/voidlinux:${{ matrix.tag }}" }
    needs: bootstrap
    runs-on: ubuntu-latest
    steps: *docker-steps
    strategy:
      fail-fast: false
      matrix:
        platform:
          - amd64
        tag:
          - amd64-latest
          - armhf-latest
