  shell:
    needs: bootstrap
    runs-on: windows-2019
    steps:
      - uses: actions/download-artifact@v2
        with: { name: bootstrap-output }
      - name: Setup tmate session
        uses: mxschmitt/action-tmate@v3
