name: Build `libstat.a`
on: [push]
jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-18.04, ubuntu-20.04, macos-10.15, macos-11, windows-2019, windows-2022]
        # TODO: arch: ...
    steps:
      - if: ${{ runner.os == 'macOS' }}
        run: |
          brew install autoconf@2.69
          brew install automake
          which aclocal
      - uses: actions/checkout@v2
      - run: bin/bootstrap
      - run: ./configure
      - run: make
