  is-act:
    runs-on: ubuntu-latest
    outputs: { result: "${{ env.ACT }}" }
    steps: [{ run: true }] ## Keep the schema happy

  android:
    needs: [bootstrap, is-act]
    runs-on: ${{ needs.is-act.outputs.result && 'ubuntu-latest' || 'macos-latest' }}
    strategy:
      fail-fast: false
      matrix:
        target: ## Choose only one of these, depending on your device...
          # - aarch64-linux-android
          # - armv7a-linux-androideabi
          - i686-linux-android
          # - x86_64-linux-android
        api: ## minSdkVersion
          # - 15
          # - 16
          # - 17
          # - 18
          # - 19
          # - 20
          # - 21
          # - 22
          # - 23
          # - 24
          # - 25
          # - 26
          # - 27
          # - 28
          - 29
          # - 30
          # - 31
    env:
      API: ${{ matrix.api }}
      NDK: 23.1.7779620 # TODO: auto-detect
      TARGET: ${{ matrix.target }}

      ANDROID_DIR: /data/local/tmp

    steps:
      - if: ${{ env.ACT }}
        run: |
          ANDROID_SDK_ROOT=/usr/local/lib/android/sdk
          echo "ANDROID_SDK_ROOT=$ANDROID_SDK_ROOT" >> $GITHUB_ENV

          sudo mkdir -p "$ANDROID_SDK_ROOT"
          sudo chmod a+rwx "$ANDROID_SDK_ROOT"

          sudo apt-get update
          sudo apt-get install --assume-yes openjdk-11-jre
      - uses: actions/download-artifact@v2
        with: { name: bootstrap-output }
      - run: tar -xvf fileinfo.tar
      - uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: ${{ env.API }}
          ndk: ${{ env.NDK }}
          # target: TODO
          # arch: TODO
          # profile: TODO
          script: |
            ./configure-android --host="${{ env.TARGET }}"
            cat src/config.h
            cat src/headers.h
            cat src/fileinfo/static.h
            make
            make check

            adb push fileinfo-fields-dynamic "$ANDROID_DIR"/
            adb shell chmod a+x "$ANDROID_DIR"/fileinfo-fields-dynamic
            adb shell "$ANDROID_DIR"/fileinfo-fields-dynamic

            adb push fileinfo-file-dynamic "$ANDROID_DIR"/tmp/
            adb shell chmod a+x "$ANDROID_DIR"/fileinfo-file-dynamic
            adb shell "$ANDROID_DIR"/fileinfo-file-dynamic .
