  is-act:
    runs-on: ubuntu-latest
    outputs:
      result: ${{ env.ACT }}

  android:
    needs: [bootstrap, is-act]
    runs-on: ${{ needs.is-act.outputs.result && 'ubuntu-latest' || 'macos-latest' }}
    strategy:
      fail-fast: false
      matrix:
        api:
          # - 15
          # - 16
          # - 17
          # - 18
          # - 19
          # - 20
          # - 21
          # - 22
          # - 23
          # - 24
          # - 25
          # - 26
          # - 27
          # - 28
          - 29
          # - 30
          # - 31
    env:
      API: ${{ matrix.api }} # 15-31 ## minSdkVersion
      NDK: 23.1.7779620 # TODO: auto-detect

      ## Only choose one of these, depending on your device...
      # TARGET: aarch64-linux-android
      # TARGET: armv7a-linux-androideabi
      TARGET: i686-linux-android
      # TARGET: x86_64-linux-android

    steps:
      - if: ${{ env.ACT }}
        run: |
          ANDROID_SDK_ROOT=/usr/local/lib/android/sdk
          echo "ANDROID_SDK_ROOT=$ANDROID_SDK_ROOT" >> $GITHUB_ENV

          sudo mkdir -p "$ANDROID_SDK_ROOT"
          sudo chmod a+rwx "$ANDROID_SDK_ROOT"

          sudo apt-get update
          sudo apt-get install --assume-yes openjdk-11-jre
      - uses: actions/download-artifact@v2
        with: { name: bootstrap-output }
      - run: tar -xvf fileinfo.tar
      - uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: ${{ env.API }}
          ndk: ${{ env.NDK }}
          # target: TODO
          # arch: TODO
          # profile: TODO
          script: |
            ./configure-android --host="${{ env.TARGET }}"
            cat src/config.h
            cat src/headers.h
            cat src/fileinfo/static.h
            make
            make check

            adb push fileinfo-fields-dynamic /data/local/tmp/
            adb shell chmod a+x /data/local/tmp/fileinfo-fields-dynamic
            adb shell /data/local/tmp/fileinfo-fields-dynamic

            adb push fileinfo-file-dynamic /data/local/tmp/
            adb shell chmod a+x /data/local/tmp/fileinfo-file-dynamic
            adb shell /data/local/tmp/fileinfo-file-dynamic .
