## Docker images from https://hub.docker.com/u/multiarch and https://github.com/multiarch
##
## Omitted images:
##
## - qemu-user-static - The binaries for QEMU
## - crossbuild - Environment for producing binaries for multiple architectures
## - true - Contains just the `true` program
## - goxc - Build tool for Go
## - bussybox - Has no package manager

  docker-multiarch-alpine:
    env: { image: "multiarch/alpine:${{ matrix.arch }}-${{ matrix.version }}" }
    needs: bootstrap
    runs-on: ubuntu-latest
    steps: *docker-steps
    strategy:
      fail-fast: false
      matrix:
        platform:
          - amd64
        arch:
          - aarch64
          - amd64
          - arm64
          - armhf
          - armv7
          - i386
          - ppc64le
          - x86
          - x86_64
        version:
          - latest-stable
          - edge
          - v3.14
          - v3.13
          - v3.12
          - v3.11

  docker-multiarch-ubuntu-core:
    env: { image: "multiarch/ubuntu-core:${{ matrix.arch }}-${{ matrix.version }}" }
    needs: bootstrap
    runs-on: ubuntu-latest
    steps: *docker-steps
    strategy:
      fail-fast: false
      matrix:
        platform:
          - amd64
        arch:
          - amd64
          - arm64
          - armhf
          - i386
          - ppc64el
          - s390x
          - x86
          - x86_64
        version:
          - bionic
          - focal
          - hirsute
          - trusty
          - xenial
        exclude:
          - { arch: amd64, version: hirsute }
          - { arch: i386, version: focal }
          - { arch: i386, version: hirsute }
          - { arch: s390, version: trusty }
          - { arch: s390, version: xenial }
          - { arch: x86, version: focal }
          - { arch: x86, version: hirsute }

  docker-multiarch-ubuntu-debootstrap:
    env: { image: "multiarch/ubuntu-debootstrap:${{ matrix.arch }}-${{ matrix.version }}-slim" }
    needs: bootstrap
    runs-on: ubuntu-latest
    steps: *docker-steps
    strategy:
      fail-fast: false
      matrix:
        platform:
          - amd64
        arch:
          - amd64
          - arm64
          - armhf
          - i386
          - ppc64el
          - powerpc
        version:
          - bionic
          - focal
          - hirsute
          - trusty
          - xenial
        exclude:
          - { arch: arm64, version: hirsute }
          - { arch: powerpc, version: bionic }
          - { arch: powerpc, version: focal }
          - { arch: powerpc, version: hirsute }

  docker-multiarch-debian-debootstrap:
    env: { image: "multiarch/debian-debootstrap:${{ matrix.arch }}-${{ matrix.version }}-slim" }
    needs: bootstrap
    runs-on: ubuntu-latest
    steps: *docker-steps
    strategy:
      fail-fast: false
      matrix:
        platform:
          - amd64
        arch:
          - amd64
          - arm64
          - armel
          - armhf
          - i386
          - mips
          - mips64el
          - mipsel
          - ppc64el
          - s390x
        version:
          - bullseye
          - buster
          - sid
          - stretch
        include:
          - { arch: powerpc, version: sid-slim }

  docker-multiarch-fedora:
    env: { image: "multiarch/fedora:${{ matrix.version }}-${{ matrix.arch }}" }
    needs: bootstrap
    runs-on: ubuntu-latest
    steps: *docker-steps
    strategy:
      fail-fast: false
      matrix:
        platform:
          - amd64
        arch:
          - aarch64
          - ppc64le
          - s390x
          - x86_64
        version:
          - 34
          - 33
          - 32
          - 31
          - 30
          - 29
        exclude:
          - { arch: ppc64le, version: 30 }
          - { arch: ppc64le, version: 31 }
          - { arch: ppc64le, version: 32 }

  docker-multiarch-centos:
    env: { image: "multiarch/centos:${{ matrix.version }}-iso-slim" }
    needs: bootstrap
    runs-on: ubuntu-latest
    steps: *docker-steps
    strategy:
      fail-fast: false
      matrix:
        platform:
          - amd64
        version:
          - 7
          - 7-aarch64
          - 7-amd64
          - 7-armhfp
          - 7-i386
          - 7-ppc64
          - 7-ppc64le
          - 7.3
          - 7.3-aarch64
          - 7.3-amd64
          - 7.3-armhfp
          - 7.3-ppc64
          - 7.3-ppc64le
          - 7.6
          - 7.6-amd64
          - 7.6-armhfp
          - aarch64
          - amd64
          - armhfp
          - i386
          - latest
          - ppc64
          - ppc64le

  docker-multiarch-voidlinux:
    env: { image: "multiarch/voidlinux:${{ matrix.tag }}" }
    needs: bootstrap
    runs-on: ubuntu-latest
    steps: *docker-steps
    strategy:
      fail-fast: false
      matrix:
        platform:
          - amd64
        tag:
          - amd64-latest
          - armhf-latest
