## Docker images from https://hub.docker.com/u/multiarch and https://github.com/multiarch
##
## Omitted images:
##
## - multiarch/qemu-user-static - The binaries for QEMU
## - multiarch/crossbuild - Environment for producing binaries for multiple architectures
## - multiarch/true - Contains just the `true` program
## - multiarch/goxc - Build tool for Go
## - multiarch/bussybox - Has no package manager

  docker-multiarch-alpine:
    env: { image: "multiarch/alpine:${{ matrix.arch }}-${{ matrix.version }}" }
    needs: bootstrap
    runs-on: ubuntu-latest
    steps: *docker-steps
    strategy:
      fail-fast: false
      matrix:
        platform:
          - amd64
        arch:
          - aarch64
          - amd64
          - arm64
          - armhf
          - armv7
          - i386
          - ppc64le
          - x86
          - x86_64
        version:
          - latest-stable
          - edge
          - v3.14
          - v3.13
          - v3.12
          - v3.11

  docker-multiarch-ubuntu-core:
    env: { image: "multiarch/ubuntu-core:${{ matrix.arch }}-${{ matrix.version }}" }
    needs: bootstrap
    runs-on: ubuntu-latest
    steps: *docker-steps
    strategy:
      fail-fast: false
      matrix:
        platform:
          - amd64
        arch:
          - amd64
          - arm64
          - armhf
          - i386
          - ppc64el
          - s390x
          - x86
          - x86_64
        version:
          - bionic
          - focal
          - hirsute
          - trusty
          - xenial
        exclude:
          - { arch: amd64, version: hirsute }
          - { arch: i386, version: focal }
          - { arch: i386, version: hirsute }
          - { arch: s390x, version: trusty }
          - { arch: s390x, version: xenial }
          - { arch: x86, version: focal }
          - { arch: x86, version: hirsute }

  docker-multiarch-ubuntu-debootstrap:
    env: { image: "multiarch/ubuntu-debootstrap:${{ matrix.arch }}-${{ matrix.version }}-slim" }
    needs: bootstrap
    runs-on: ubuntu-latest
    steps: *docker-steps
    strategy:
      fail-fast: false
      matrix:
        platform:
          - amd64
        arch:
          - amd64
          - arm64
          - armhf
          - i386
          - ppc64el
          - powerpc
        version:
          - bionic
          - focal
          - hirsute
          - trusty
          - xenial
        exclude:
          - { arch: arm64, version: hirsute }
          - { arch: powerpc, version: bionic }
          - { arch: powerpc, version: focal }
          - { arch: powerpc, version: hirsute }
          - { arch: powerpc, version: trusty } # doesn't stay running
          - { arch: powerpc, version: xenial } # doesn't stay running

  docker-multiarch-debian-debootstrap:
    env: { image: "multiarch/debian-debootstrap:${{ matrix.arch }}-${{ matrix.version }}-slim" }
    needs: bootstrap
    runs-on: ubuntu-latest
    steps: *docker-steps
    strategy:
      fail-fast: false
      matrix:
        platform:
          - amd64
        arch:
          - amd64
          - arm64
          - armel
          - armhf
          - i386
          ## - mips # doesn't stay running
          - mips64el
          ##- mipsel # doesn't stay running
          - ppc64el
          - s390x
        version:
          - bullseye
          - buster
          - sid
          - stretch
        ## include:
          ## - { platform: amd64, arch: powerpc, version: sid } # doesn't stay running

  docker-multiarch-fedora:
    env: { image: "multiarch/fedora:${{ matrix.version }}-${{ matrix.arch }}" }
    needs: bootstrap
    runs-on: ubuntu-latest
    steps: *docker-steps
    strategy:
      fail-fast: false
      matrix:
        platform:
          - amd64
        arch:
          - aarch64
          - ppc64le
          - s390x
          - x86_64
        version:
          - 34
          - 33
          - 32
          - 31
          - 30
          - 29
        exclude:
          - { arch: ppc64le, version: 30 }
          - { arch: ppc64le, version: 31 }
          - { arch: ppc64le, version: 32 }

  docker-multiarch-centos:
    env: { image: "multiarch/centos:${{ matrix.version }}-iso-slim" }
    needs: bootstrap
    runs-on: ubuntu-latest
    steps: *docker-steps
    strategy:
      fail-fast: false
      matrix:
        platform:
          - amd64
        version:
          - 7 # works
          - 7-aarch64 # works
          - 7-amd64 # works
          ## - 7-armhfp # yum segfaults
          ## - 7-i386 # doesn't stay running
          ## - 7-ppc64 # doesn't stay running
          ## - 7-ppc64le # doesn't stay running
          - 7.3 # works
          - 7.3-aarch64 # works
          - 7.3-amd64 # works
          ## - 7.3-armhfp # yum segfaults
          ## - 7.3-ppc64 # doesn't stay running
          ## - 7.3-ppc64le # doesn't stay running
          - 7.6 # works
          - 7.6-amd64 # works
          ## - 7.6-armhfp # yum segfaults
          - aarch64 # works
          - amd64 # works
          ## - armhfp # yum segfaults
          ## - i386 # doesn't stay running
          - latest # works
          ## - ppc64 # doesn't stay running
          ## - ppc64le # doesn't stay running

  docker-multiarch-voidlinux:
    env: { image: "multiarch/voidlinux:${{ matrix.tag }}" }
    needs: bootstrap
    runs-on: ubuntu-latest
    steps: *docker-steps
    strategy:
      fail-fast: false
      matrix:
        platform:
          - amd64
        tag:
          - amd64-latest
          - armhf-latest
