  mobile-android:
    needs: [bootstrap, is-act]
    runs-on: ${{ needs.is-act.outputs.result && 'ubuntu-latest' || 'macos-latest' }}
    strategy:
      fail-fast: false
      matrix:
        ndk:
          # - '16.1.4479499'
          - '23.1.7779620'
        arch:
          ## - armeabi-v7a # unsupported by android-emulator-runner
          # - arm64-v8a # (require Android 4.2+ (API 17+) and are limited to fewer API levels (e.g. 30))
          # - x86
          - x86_64 # (requires: API 21+)
        type: # Device type
          - default # works (API 29)
          # - google_apis # works (API 29)
          # - playstore # works (API 29)
          # - android-wear
          # - android-wear-cn
          # - android-tv # works (API 29)
          # - google-tv
          ## - aosp_atd (requires: api-level: 30, arch: x86)
          ## - google_atd (requires: api-level: 30, arch: x86)
        api: # Minimum API android-emulator-runner supports is 15 (Android 4.0.3)
          # - 15 # clang missing from NDK 23 +

          # - 16 # works: x86/default/llvm
          # - 17 # works: x86/default/llvm
          # - 18 # works: x86/default/llvm +
          # - 19 # works: x86/default/llvm +
          # - 20 # Failed to find package 'system-images;android-20;default;x86'
          # - 21 # works: x86/default/llvm
          # - 22 # works: x86/default/llvm +
          # - 23 # works: x86/default/llvm
          # - 24 # works: x86/default/llvm
          # ##- 25 # clang missing from NDK 23
          - 26 # works: x86/default/llvm +
          # - 27 # works: x86/default/llvm?
          # - 28 # works: x86/default/llvm +
          # - 29 # works: x86/default/llvm +
          ## - 30 # Failed to find package 'system-images;android-30;default;x86'
          ## - 31 # Failed to find package 'system-images;android-31;default;x86'
    env:
      API: ${{ matrix.api }}
      ARCH: ${{ matrix.arch }}
      # NDK: ${{ '16.1.4479499' }}
      # NDK: ${{ '23.1.7779620' }}
      NDK: ${{ matrix.ndk }}
      # NDK: ${{ matrix.api <= 19 && '16.1.4479499' || '23.1.7779620' }}
        # https://developer.android.com/ndk/downloads/revision_history
        # https://github.com/android/ndk/wiki/Unsupported-Downloads
        # Android NDK r16b (December 2017) (API 14-27) NDK: 16.1.4479499
        # Android NDK r23 LTS (August 2021) (API 16+) NDK: 23.1.7779620

      DEST_DIR: /data/local/tmp # A directory which is writable and not noexec

    steps:
      ## Ensure $ANDROID_SDK_ROOT is setup as it is missing on `act`
      - run: echo "ANDROID_SDK_ROOT=${ANDROID_SDK_ROOT:-/usr/local/lib/android/sdk}" >> $GITHUB_ENV
      - run: sudo mkdir -p "$ANDROID_SDK_ROOT" || true
      - run: sudo chmod a+rwx "$ANDROID_SDK_ROOT"

      - if: ${{ env.ACT }}
        run: sudo apt-get update
      - if: ${{ env.ACT }}
        run: sudo apt-get install --assume-yes default-jre # Needed by android-emulator-runner
      - if: ${{ env.ACT }}
        run: sudo apt-get install --assume-yes libncurses5 # Some `clang` need this

      - uses: actions/download-artifact@v2
        with: { name: bootstrap-output }
      - run: tar -xvf fileinfo.tar

      - uses: reactivecircus/android-emulator-runner@v2
        with:
          arch: ${{ matrix.arch }}
          target: ${{ matrix.type }}
          api-level: ${{ env.API }}
          ndk: ${{ env.NDK }}
          script: |
            # $ANDROID_SDK_ROOT/cmdline-tools/latest/bin/sdkmanager --list --verbose --include_obsolete
            .github/configure-android
            cat src/config.h
            cat src/headers.h
            cat src/fileinfo/static.h
            make
            make check

            file fileinfo-fields-dynamic
            file fileinfo-file-dynamic

            adb push fileinfo-fields-dynamic "$DEST_DIR"/
            adb shell chmod a+x "$DEST_DIR"/fileinfo-fields-dynamic
            adb shell "$DEST_DIR"/fileinfo-fields-dynamic

            adb push fileinfo-file-dynamic "$DEST_DIR"/
            adb shell chmod a+x "$DEST_DIR"/fileinfo-file-dynamic
            adb shell ls -al "$DEST_DIR"/fileinfo-file-dynamic
            adb shell "$DEST_DIR"/fileinfo-file-dynamic "$DEST_DIR"/fileinfo-file-dynamic
