  shell:
    needs: bootstrap
    runs-on:
      # - windows-2022
      # - windows-2019
      # - windows-2016
      # - macos-11
      - macos-10.15
    steps:
      - uses: actions/download-artifact@v2
        with: { name: bootstrap-output }
      - uses: mxschmitt/action-tmate@v3
